### ISSUE TITLE
New UI not functional

### ISSUE THREAD

**Issue by Hypxria** [StarBobis/DBMT#1]
The new menu you have introduced causes issues. Specifically, it is not possible to see nor select any functions seen in your image. Ran using instructions presented.
您引入的新菜单会导致问题。具体来说，无法查看或选择图像中显示的任何功能。按照提供的说明运行。
![Screenshot 2024-11-23 184654](https://github.com/user-attachments/assets/aed52d8c-e87a-4c3e-ad7d-6d7048a9e91b)
Windows 11

**Comment by StarBobis** [comment]
yes I'm not even start to develop any function, try use released old DBMT, new UI DBMT will develop later.
https://github.com/StarBobis/DBMT/releases

**Comment by Hypxria** [comment]
oh okay thank you, is there a translation for old?

**Comment by StarBobis** [comment]
thanks for feedback, will add english translate later.

**Comment by StarBobis** [comment]
New UI has transfer to use WinUI3 & C# to develop, it takes less code and much more easier, new UI's github: https://github.com/StarBobis/DirectX-BufferModTool

This issue will be closed because this repository will archived and all develop will move to new repository, thanks for your feedback.
